
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - monitoring_network
    environment:
      - DOCKER_ENV=true  # Adicionado para indicar execução no Docker
    entrypoint: python app.py

  db:
    image: postgres:17-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: escola
      POSTGRES_USER: faat
      POSTGRES_PASSWORD: faat
    ports:
      - "3001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring_network

  prometheus:
    image: prom/prometheus:v2.41.0  # Alterado para uma versão específica
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - monitoring_network

  grafana:
    build:
      context: ./grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring_network

  postgres-exporter:
    image: bitnami/postgres-exporter:latest
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://faat:faat@db:5432/escola?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - db
    networks:
      - monitoring_network

volumes:
  postgres_data:
  grafana_data:

#Permite comunicação entre os serviços/containers
# e isola a rede de monitoramento dos outros containers
networks:
  monitoring_network:
    driver: bridge


