-- Tabela "Professor": Representa os professores da escola.
-- id_professor: Identificador único do professor (chave primária).
-- nome_completo: Nome completo do professor.
-- email: Endereço de e-mail do professor.
-- telefone: Telefone de contato do professor.
CREATE TABLE "Professor" (
  "id_professor" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_completo" varchar(255),
  "email" varchar(100),
  "telefone" varchar(20)
);

-- Tabela "Disciplina": Representa as disciplinas oferecidas pela escola.
-- id_disciplina: Identificador único da disciplina (chave primária).
-- nome_disciplina: Nome da disciplina.
-- codigo: Código único da disciplina.
-- carga_horaria: Carga horária total da disciplina.
CREATE TABLE "Disciplina" (
  "id_disciplina" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_disciplina" varchar(100),
  "codigo" varchar(20) UNIQUE,
  "carga_horaria" int
);

-- Tabela "Turma": Representa as turmas da escola.
-- id_turma: Identificador único da turma (chave primária).
-- nome_turma: Nome da turma.
-- id_professor: Chave estrangeira para o professor responsável pela turma.
-- horario: Horário das aulas da turma.
-- ano_letivo: Ano letivo da turma.
-- id_disciplina: Chave estrangeira para a disciplina associada à turma.
CREATE TABLE "Turma" (
  "id_turma" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_turma" varchar(50),
  "id_professor" int,
  "horario" varchar(100),
  "ano_letivo" int,
  "id_disciplina" int
);

-- Tabela "Alunos": Representa os alunos matriculados na escola.
-- id_aluno: Identificador único do aluno (chave primária).
-- nome_completo: Nome completo do aluno.
-- data_nascimento: Data de nascimento do aluno.
-- id_turma: Chave estrangeira para a turma do aluno.
-- nome_responsavel: Nome do responsável pelo aluno.
-- telefone_responsavel: Telefone do responsável.
-- email_responsavel: E-mail do responsável.
-- informacoes_adicionais: Informações adicionais sobre o aluno.
CREATE TABLE "Alunos" (
  "id_aluno" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_completo" varchar(255),
  "data_nascimento" date,
  "id_turma" int,
  "nome_responsavel" varchar(255),
  "telefone_responsavel" varchar(20),
  "email_responsavel" varchar(100),
  "informacoes_adicionais" text
);

-- Tabela "Pagamento": Representa os pagamentos realizados pelos alunos.
-- id_pagamento: Identificador único do pagamento (chave primária).
-- id_aluno: Chave estrangeira para o aluno que realizou o pagamento.
-- data_pagamento: Data do pagamento.
-- valor_pago: Valor pago.
-- forma_pagamento: Forma de pagamento utilizada.
-- referencia: Referência do pagamento.
-- status: Status do pagamento (ex.: pago, pendente).
CREATE TABLE "Pagamento" (
  "id_pagamento" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_aluno" int,
  "data_pagamento" date,
  "valor_pago" decimal(10,2),
  "forma_pagamento" varchar(50),
  "referencia" varchar(100),
  "status" varchar(20)
);

-- Tabela "Presenca": Representa o registro de presença dos alunos.
-- id_presenca: Identificador único do registro de presença (chave primária).
-- id_aluno: Chave estrangeira para o aluno.
-- data_presenca: Data da presença.
-- presente: Indica se o aluno esteve presente (true/false).
CREATE TABLE "Presenca" (
  "id_presenca" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_aluno" int,
  "data_presenca" date,
  "presente" boolean
);

-- Tabela "Atividade": Representa as atividades realizadas na escola.
-- id_atividade: Identificador único da atividade (chave primária).
-- descricao: Descrição da atividade.
-- data_realizacao: Data de realização da atividade.
CREATE TABLE "Atividade" (
  "id_atividade" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descricao" text,
  "nome_turma" varchar(50),
  "data_realizacao" date
);

-- Tabela "Atividade_Aluno": Representa a relação entre atividades e alunos.
-- id_atividade: Chave estrangeira para a atividade.
-- id_aluno: Chave estrangeira para o aluno.
-- Chave primária composta por id_atividade e id_aluno.
CREATE TABLE "Atividade_Aluno" (
  "id_atividade" int,
  "id_aluno" int,
  "primary" key(id_atividade,id_aluno)
);

-- Tabela "Nota": Representa as notas dos alunos em disciplinas.
-- id_nota: Identificador único da nota (chave primária).
-- id_aluno: Chave estrangeira para o aluno.
-- id_disciplina: Chave estrangeira para a disciplina.
-- nota: Nota obtida pelo aluno.
-- data_lancamento: Data de lançamento da nota.
CREATE TABLE "Nota" (
  "id_nota" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_aluno" int,
  "id_disciplina" int,
  "nota" decimal(5,2),
  "data_lancamento" date
);

-- Tabela "Usuario": Representa os usuários do sistema.
-- id_usuario: Identificador único do usuário (chave primária).
-- login: Nome de login do usuário (único).
-- senha: Senha do usuário.
-- nivel_acesso: Nível de acesso do usuário (ex.: admin, professor).
-- id_professor: Chave estrangeira para o professor associado ao usuário.
CREATE TABLE "Usuario" (
  "id_usuario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "login" varchar(50) UNIQUE,
  "senha" varchar(255),
  "nivel_acesso" varchar(20),
  "id_professor" int
);

-- Relacionamentos e cardinalidades:
-- Um professor pode estar associado a várias turmas (1:N).
ALTER TABLE "Turma" ADD FOREIGN KEY ("id_professor") REFERENCES "Professor" ("id_professor");

-- Uma disciplina pode estar associada a várias turmas (1:N).
ALTER TABLE "Turma" ADD FOREIGN KEY ("id_disciplina") REFERENCES "Disciplina" ("id_disciplina");

-- Uma turma pode ter vários alunos (1:N).
ALTER TABLE "Alunos" ADD FOREIGN KEY ("id_turma") REFERENCES "Turma" ("id_turma");

-- Um aluno pode realizar vários pagamentos (1:N).
ALTER TABLE "Pagamento" ADD FOREIGN KEY ("id_aluno") REFERENCES "Alunos" ("id_aluno");

-- Um aluno pode ter vários registros de presença (1:N).
ALTER TABLE "Presenca" ADD FOREIGN KEY ("id_aluno") REFERENCES "Alunos" ("id_aluno");

-- Uma atividade pode ser realizada por vários alunos (N:M).
ALTER TABLE "Atividade" ADD FOREIGN KEY ("id_turma") REFERENCES "Turma" ("id_turma");

-- Uma atividade pode estar associada a uma turma específica (1:N).
ALTER TABLE "Atividade" ADD CONSTRAINT fk_turma FOREIGN KEY (id_turma) REFERENCES "Turma"(id_turma);

-- Uma atividade pode estar associada a vários alunos e vice-versa (N:M).
ALTER TABLE "Atividade_Aluno" ADD FOREIGN KEY ("id_atividade") REFERENCES "Atividade" ("id_atividade");
ALTER TABLE "Atividade_Aluno" ADD FOREIGN KEY ("id_aluno") REFERENCES "Alunos" ("id_aluno");

-- Um aluno pode ter várias notas em diferentes disciplinas (1:N).
ALTER TABLE "Nota" ADD FOREIGN KEY ("id_aluno") REFERENCES "Alunos" ("id_aluno");

-- Uma disciplina pode ter várias notas associadas (1:N).
ALTER TABLE "Nota" ADD FOREIGN KEY ("id_disciplina") REFERENCES "Disciplina" ("id_disciplina");

-- Um professor pode estar associado a um usuário no sistema (1:1).
ALTER TABLE "Usuario" ADD FOREIGN KEY ("id_professor") REFERENCES "Professor" ("id_professor");
